name: hag-dta
channels:
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - networkx
  - matplotlib
  - rdkit
  - pip:
    - matplotlib==3.10.1
    - matplotlib-inline==0.1.7
    - networkx==3.4.2
    - numpy==2.2.5
    - open_clip_torch==3.2.0
    - pandas==2.2.3
    - pillow==11.2.1
    - scipy==1.17.0
    - torch @ https://download.pytorch.org/whl/cu128/torch-2.7.0%2Bcu128-cp312-cp312-manylinux_2_28_x86_64.whl#sha256=7c0f08d1c44a02abad389373dddfce75904b969a410be2f4e5109483dd3dc0ce==
    - torchvision @ https://download.pytorch.org/whl/cu128/torchvision-0.22.0%2Bcu128-cp312-cp312-manylinux_2_28_x86_64.whl#sha256=06c101f40e1ff94869be14487c91fd5352e376f202fdeafb8f53c58cee2fbeb5==
